/*
 * Copyright 2020 Aiven Oy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.aiven.commons.kafka.connector.sink.grouper;

import java.util.Objects;
import org.apache.kafka.connect.sink.SinkRecord;

/**
 * Groups {@link SinkRecord}s by generating keys from templates. Each record will produce a key for
 * the group that it belongs to.
 */
public abstract class RecordGrouper {

  /** the key for grouping the records */
  private final RecordGrouperKey grouperKey;

  /**
   * Creates the RecordGroup using the specified RecordGrouperKey.
   *
   * @param grouperKey the RecordGrouperKey to use to group records.
   */
  protected RecordGrouper(final RecordGrouperKey grouperKey) {
    Objects.requireNonNull(grouperKey, "grouperKey cannot be null");
    this.grouperKey = grouperKey;
  }

  /**
   * Adds the record to the proper group.
   *
   * @param record record to add to the group.
   * @return the group key associated with the record.
   */
  public final String put(final SinkRecord record) {
    Objects.requireNonNull(record, "record cannot be null");
    return put(grouperKey.createKey(record), record);
  }

  /**
   * Associate the record with the appropriate collection. Implementation of the collection is left
   * to the concrete class.
   *
   * @param key The key generated by the grouper.
   * @param record record to add to the group specified by the key.
   * @return the group key associated with the record.
   */
  protected abstract String put(String key, SinkRecord record);
}
