package io.aiven.commons.kafka.connector.source;

import static org.assertj.core.api.Assertions.assertThat;

import io.aiven.commons.kafka.config.fragment.CommonConfigFragment;
import io.aiven.commons.kafka.connector.source.config.SourceConfigFragment;
import io.aiven.commons.kafka.connector.source.extractor.ByteArrayExtractor;
import io.aiven.commons.kafka.connector.source.task.DistributionType;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Predicate;

/**
 * An example of a TestConfig for the example code. This particular test is sending the data as
 * bytes and expecting bytes back. It could have sent bytes and expected String back
 */
public class ByteTestConfig extends TestConfig {

  /**
   * The test storage that this config is reading. This is an artifact of this example and in
   * reality would probably be a client to a remote storage system like S3 or Salesforce. However,
   * in some cases, it may be advisable to use a SourceStorage, but that determination is
   * implementation specific.
   */
  private final TestSourceStorage storage;

  /**
   * Constructor for this test config.
   *
   * @param storage the storage to use.
   */
  public ByteTestConfig(TestSourceStorage storage) {
    super("Example Test Config");
    this.storage = storage;
  }

  @Override
  public Map<String, String> consumerConfiguration() {
    Map<String, String> workerOverrides = new HashMap<>();
    workerOverrides.put("example.dir", storage.getTestDir().toString());
    return CommonConfigFragment.setter(workerOverrides)
        .valueConverter("org.apache.kafka.connect.storage.StringConverter")
        .keyConverter("org.apache.kafka.connect.converters.ByteArrayConverter")
        .data();
  }

  @Override
  public List<SourceStorage.TestData> getTestData(int count) {
    // these tests create a series of a unique "hello world" strings, and sends the bytes as both
    // the data to send and the expected outcome.
    List<SourceStorage.TestData> result = new ArrayList<>();
    for (int i = 0; i < count; i++) {
      byte[] data = String.format("Hello world #%s", i).getBytes(StandardCharsets.UTF_8);
      result.add(new SourceStorage.TestData(data, data));
    }
    return result;
  }

  @Override
  public Map<String, String> initialConfig() {
    Map<String, String> config = new HashMap<>();
    // list the temp directory to read/write.
    config.put("example.dir", storage.getTestDir().toString());
    // set the key converter as a string and the value as a byte.
    CommonConfigFragment.setter(config)
        .valueConverter("org.apache.kafka.connect.storage.StringConverter")
        .keyConverter("org.apache.kafka.connect.converters.ByteArrayConverter");
    // use object hash distribution and the ByteArray extractor.
    SourceConfigFragment.setter(config)
        .distributionType(DistributionType.OBJECT_HASH)
        .extractorClass(ByteArrayExtractor.class);
    return config;
  }

  @Override
  public List<SourceStorage.WriteResult> writeTestData(
      String topic, List<SourceStorage.TestData> data) {
    // use the SourceStorage to create the ky and write the data with that key.
    // in general this method should take the data generated by getTestData and write it to
    // storage.
    return data.stream()
        .map(entry -> storage.writeWithKey(storage.createKey(topic, 0), (byte[]) entry.data()))
        .toList();
  }

  @Override
  public void consumeMessages(
      AbstractSourceIntegrationBase.MessageConsumer messageConsumer,
      String topic,
      List<SourceStorage.TestData> testData,
      List<SourceStorage.WriteResult> writeResults,
      Duration timeout) {
    // this implementation is returning byte[] in the test so consumer the messages as bytes.

    List<byte[]> expected =
        SourceStorage.TestData.expected(testData).stream().map(o -> (byte[]) o).toList();
    // in our case every record produces a single entry.

    Predicate<byte[]> p =
        x -> {
          for (byte[] y : expected) {
            if (Arrays.equals(x, y)) {
              return true;
            }
          }
          return false;
        };

    List<byte[]> records = messageConsumer.consumeByteMessages(topic, testData.size(), timeout);
    assertThat(records).allMatch(p);
  }
}
